public enum Nacionalidades
{
    Afghan, Albanian, Algerian, American, Andorran, Angolan, Anguillan, 
    CitizenOfAntiguaAndBarbuda, Argentine, Armenian, Australian, Austrian, Azerbaijani,
    Bahamian, Bahraini, Bangladeshi, Barbadian, Belarusian, Belgian, Belizean, Beninese,
    Bermudian, Bhutanese, Bolivian, CitizenOfBosniaAndHerzegovina, Botswanan, Brazilian,
    British, BritishVirginIslander, Bruneian, Bulgarian, Burkinan, Burmese, Burundian,
    Cambodian, Cameroonian, Canadian, CapeVerdean, CaymanIslander, CentralAfrican, 
    Chadian, Chilean, Chinese, Colombian, Comoran, Congolese, CookIslander, CostaRican,
    Croatian, Cuban, Cymraes, Cymro, Cypriot, Czech, Danish, Djiboutian, Dominican,
    CitizenOfTheDominicanRepublic, Dutch, EastTimorese, Ecuadorean, Egyptian, Emirati,
    English, EquatorialGuinean, Eritrean, Estonian, Ethiopian, Faroese, Fijian, Filipino,
    Finnish, French, Gabonese, Gambian, Georgian, German, Ghanaian, Gibraltarian, Greek,
    Greenlandic, Grenadian, Guamanian, Guatemalan, CitizenOfGuineaBissau, GuineanGuyanese,
    Haitian, Honduran, HongKonger, Hungarian, Icelandic, Indian, Indonesian, Iranian,
    Iraqi, Irish, Israeli, Italian, Ivorian, Jamaican, Japanese, Jordanian,
    Kazakh, Kenyan, Kittitian, CitizenOfKiribati, Kosovan, Kuwaiti, Kyrgyz,
    Lao, Latvian, Lebanese, Liberian ,Libyan, LiechtensteinCitizen, Lithuanian, 
    Luxembourger, Macanese, Macedonian, Malagasy, Malawian, Malaysian, Maldivian, Malian,
    Maltese, Marshallese, Martiniquais, Mauritanian, Mauritian, Mexican, Micronesian, 
    Moldovan, Monegasque, Mongolian, Montenegrin, Montserratian, Moroccan, Mosotho, 
    Mozambican, Namibian, Nauruan, Nepalese, NewZealander, Nicaraguan, Nigerian, Nigerien,
    Niuean, NorthKorean, NorthernIrish, Norwegian, Omani, Pakistani, Palauan, Palestinian, 
    Panamanian, PapuaNewGuinean, Paraguayan, Peruvian, PitcairnIslander, Polish, Portuguese,
    Prydeinig, PuertoRican, Qatari, Romanian, Russian, Rwandan, Salvadorean, Sammarinese, 
    Samoan, SaoTomean, SaudiArabian, Scottish, Senegalese, Serbian, CitizenOfSeychelles, 
    SierraLeonean, Singaporean, Slovak, Slovenian, SolomonIslander, Somali, SouthAfrican,
    SouthKorean, SouthSudanese, Spanish, SriLankan, StHelenian, StLucian, Stateless, Sudanese,
    Surinamese, Swazi, Swedish, Swiss, Syrian, Taiwanese, Tajik, Tanzanian, Thai, Togolese, 
    Tongan, Trinidadian, Tristanian, Tunisian, Turkish, Turkmen, TurksAndCaicosIslander,
    Tuvaluan, Ugandan, Ukrainian, Uruguayan, Uzbek, VaticanCitizen, CitizenOfVanuatu, 
    Venezuelan, Vietnamese, Vincentian, Wallisian, Welsh, Yemeni, Zambian, Zimbabwean
}